### ISSUE TITLE
Why is this a copy of Apollo code gen?

### ISSUE THREAD

**Issue by abhiaiyer91** [awslabs/aws-appsync-codegen#1]
There are a lot of hard open source contributors working on codegen, what’s the aim of this repo? At least put some attribution to the original repo that you ripped off.

**Comment by digitalbuddha** [comment]
I'm also confused about this. Any reason why https://github.com/awslabs/aws-appsync-codegen/blob/master/NOTICE has it as copyright amazon while the contributing.md is still apollo's as is the license.md?

**Comment by minbi** [comment]
Attribution has been corrected in the NOTICE file.
The intent was for this code to remain under the license that apollo-codegen was under.
If and when a pull request is possible, then changes here could be merged back.

Please re-open if there are further issues.

**Comment by stubailo** [comment]
That's great to hear that the code in here will be MIT licensed!
