### ISSUE TITLE
Ambiguous use of 'map' in generated Swift file

### ISSUE THREAD

**Issue by richienko** [awslabs/aws-appsync-codegen#12]
I'm getting this error when trying to run project in `struct Item: GraphQLSelectionSet` in constructor.
.graphql and .json schema files are valid, since they are the same as which I'm using successfully in android project.

As I read [here](https://github.com/apollographql/apollo-ios/issues/178), this should be fixed in apollo-codegen 0.18.7.

Edit:
Contructor with error looks like this:
```
public init(id: GraphQLID, customerId: String, assignedEntityId: String? = nil, tourId: String? = nil, dueDate: String? = nil, windowStart: String? = nil, windowEnd: String? = nil, status: String? = nil, jobInfo: [JobInfo?]? = nil, statusTransitions: [StatusTransition?]? = nil, tasks: [Task?]? = nil) {
          self.init(snapshot: ["__typename": "Job", "id": id, "customerId": customerId, "assignedEntityId": assignedEntityId, "tourId": tourId, "dueDate": dueDate, "windowStart": windowStart, "windowEnd": windowEnd, "status": status,
                               "jobInfo": jobInfo.flatMap { $0.map { $0.flatMap { $0.snapshot } } },
                               "statusTransitions": statusTransitions.flatMap { $0.map { $0.flatMap { $0.snapshot } } },
                               "tasks": tasks.flatMap { $0.map { $0.flatMap { $0.snapshot } } }])
}
```
Fixed constructor by manual edit:
```
public init(id: GraphQLID, customerId: String, assignedEntityId: String? = nil, tourId: String? = nil, dueDate: String? = nil, windowStart: String? = nil, windowEnd: String? = nil, status: String? = nil, jobInfo: [JobInfo?]? = nil, statusTransitions: [StatusTransition?]? = nil, tasks: [Task?]? = nil) {
	let jobInfoMap = jobInfo.flatMap { $0.map { $0.flatMap { $0.snapshot } } }
	let statusTransitions = statusTransitions.flatMap { $0.map { $0.flatMap { $0.snapshot } } }
	let tasks = tasks.flatMap { $0.map { $0.flatMap { $0.snapshot } } }
	
	self.init(snapshot: ["__typename": "Job", "id": id, "customerId": customerId, "assignedEntityId": assignedEntityId, "tourId": tourId, "dueDate": dueDate, "windowStart": windowStart, "windowEnd": windowEnd, "status": status,
						 "jobInfo": jobInfoMap,
						 "statusTransitions": statusTransitions,
						 "tasks": tasks
						])
}
```

**Comment by undefobj** [comment]
Hello @richienko 

We will be retiring this repo soon as the new [AWS Amplify CLI](url
https://github.com/aws-amplify/amplify-cli) has the codegen features, improvements, and more, including automatic graphql generation as well as a GraphQL transformer:
https://github.com/aws-amplify/amplify-cli/blob/master/native_guide.md

Could you look to see if the new AWS Amplify CLI flow resolves your issue and if not open something in that repo?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If you still need help, please open an issue on the new [AWS Amplify CLI ](https://github.com/aws-amplify/amplify-cli) repo, which provides the codegen features and more.
