### ISSUE TITLE
Type AWSDateTime not found in document

### ISSUE THREAD

**Issue by wyjiao** [awslabs/aws-appsync-codegen#17]
We are using the AWS AppSync scalar type of 'AWSDateTime'. When trying to generate Typescript types, we run into an error of 'Type AWSDateTime not found in document'.

**Comment by undefobj** [comment]
Hello @wyjiao 

We will be retiring this repo soon as the new [AWS Amplify CLI](url
https://github.com/aws-amplify/amplify-cli) has the codegen features and more, including automatic graphql generation as well as a GraphQL transformer:
https://github.com/aws-amplify/amplify-cli/blob/master/native_guide.md

Could you look to see if the new AWS Amplify CLI flow resolves your issue and if not open something in that repo? The custom scalar types are being addressed there.

**Comment by wyjiao** [comment]
Hi @undefobj

Thanks for the information. I tried the AWS Amplify CLI, it works with the 'AWSDateTime' and transform into the String type in typescript.

However, to use the amplify CLI, it forces me to do 'amplify init' which creates AuthRoles, DeploymentBucket, cloudformation stack etc. We already have these infrastructures configured and managed in a separate package, and the only feature we need is code gen. 

Is there  a way to avoid setting up the infrastructures, but only generate codegen types?

**Comment by undefobj** [comment]
@wyjiao potentially, could you open an issue on the Amplify CLI repo to request this as a feature with your use case so the team can prioritize accordingly?

**Comment by wyjiao** [comment]
Sure. I'll open one there. Thanks.
