### ISSUE TITLE
snake_case GraphQLMap field names incorrectly camelCased in getters and setters in Swift

### ISSUE THREAD

**Issue by sirshannon** [awslabs/aws-appsync-codegen#18]
in Swift, when an appSync input struct has property name that is snake_case in a schema like:
```
input SomeItem {
	item_id: Int!
}
```
 the generated Swift code is expected to look like this:

```
public struct SomeItem: GraphQLMapConvertible {
  public var graphQLMap: GraphQLMap

  public init(itemId: Int) {
    graphQLMap = ["item_id": itemId]
  }

  public var itemId: Int {
    get {
      return graphQLMap["item_id"] as! Int
    }
    set {
      graphQLMap.updateValue(newValue, forKey: "item_id")
    }
  }
}
```
but looks like this:

```
public struct SomeItem: GraphQLMapConvertible {
  public var graphQLMap: GraphQLMap

  public init(itemId: Int) {
    graphQLMap = ["item_id": itemId]
  }

  public var itemId: Int {
    get {
      return graphQLMap["itemId"] as! Int
    }
    set {
      graphQLMap.updateValue(newValue, forKey: "itemId")
    }
  }
}
```

due to /src/swift/codeGeneration.ts line 843 using `name` as the property name (e.g. `item_id`) but lines 856 and 860 using `propertyName` as property name (e.g. `itemId`).

This causes the `get` methods to crash the app due to nil values when force unwrapping (which is why some people don't force unwrap in these cases and opt for nil checks in failable inits instead).

I don't use node if possible and have never used TypeScript so I can't help more than this.  The fix I'm using now isn't pretty :(

**Comment by undefobj** [comment]
Hello @sirshannon 

We will be retiring this repo soon as the new [AWS Amplify CLI](https://github.com/aws-amplify/amplify-cli) has the codegen features and more, including automatic graphql generation as well as a GraphQL transformer:
https://github.com/aws-amplify/amplify-cli/blob/master/native_guide.md

Could you look to see if the new AWS Amplify CLI flow resolves your issue and if not open something in that repo so we can address it?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If you still need help, please open an issue on the new [AWS Amplify CLI ](https://github.com/aws-amplify/amplify-cli) repo, which provides the codegen features and more.
