### ISSUE TITLE
While using codegen to covert my graphql schema to swift, facing error : Directive "aws_subscribe" may not be used on FIELD_DEFINATION

### ISSUE THREAD

**Issue by dhavalsavaliya1** [awslabs/aws-appsync-codegen#19]
I am new to graphql and using aws tutorials (https://awslabs.github.io/aws-mobile-appsync-sdk-ios/) to convert the graphql appsync schema to swift supported via codegen.
Following is the graphql schema I am trying to convert:

type Author {
  firstname: String
  id: ID
  lastname: String
  posts: [Post]!
}

type Comment {
  author: Author
  created_at: String
  id: ID
  text: String
}

type Mutation {
  addComment(input: CommentAddInput!): Comment!
  addPost(input: PostAddInput!): Post!
  deleteComment(id: ID!): Comment!
  deletePost(id: ID!): Post!
  updateComment(input: CommentUpdateInput!): Comment!
  updatePost(input: PostUpdateInput!): Post!
}

type Post {
  author: Author
  comments: [Comment]!
  created_at: String
  id: ID
  text: String
}

type Query {
  getAuthor(id: ID!): Author
  getAuthors: [Author]!
  getComment(id: ID!): Comment
  getComments(post: ID!): [Comment]!
  getPost(id: ID!): Post
  getPosts(author: ID!): [Post]!
}

type Subscription {
  addedComment(author_id: ID, post_id: ID): Comment!
    @aws_subscribe(mutations:["addComment"])
  addedPost(author_id: ID!): Post!
    @aws_subscribe(mutations:["addPost"])
}

input CommentAddInput {
  author: ID!
  post: ID!
  text: String!
}

input CommentUpdateInput {
  author: ID
  id: ID!
  post: ID
  text: String
}

input PostAddInput {
  author: ID!
  text: String!
}

input PostUpdateInput {
  author: ID
  id: ID!
  text: String
}

**Comment by yuth** [comment]
aws-appsync-codegen expects the input schema to be an introspection schema file. You can download the introspection schema following these steps
1. Goto [AWS AppSync Console](https://console.aws.amazon.com/appsync/home) 
2. Select the API that you created
3. Scroll to the bottom of the page and you will see `Download` button under `Download the AWS AppSync.json config file: `

**Comment by rohandubal** [comment]
Also, your .graphql file must contain the queries/ mutations/ subscriptions you would like to use in your app. 

Example .graphql file: https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/blob/master/EventsApp/events.graphql

Example schema file: https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/blob/master/EventsApp/schema-events.json

Thanks,
Rohan

**Comment by paalex** [comment]
AWS Appsync generates @aws_subscribe decorators such as:
`@aws_subscribe(mutations: ["createMessage"])`
Removing those from schema.graphql solves the error

**Comment by undefobj** [comment]
Hello @dhavalsavaliya1

@rohandubal and @yuth are correct in that you need both an introspection schema as well as the graphql documents. We will be retiring this repo soon as the new AWS Amplify CLI has the codegen features and more, including automatic graphql generation as well as a GraphQL transformer:
https://github.com/aws-amplify/amplify-cli/blob/master/native_guide.md

Could you look to see if the new AWS Amplify CLI flow resolves your issue and if not open something in that repo?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If you still need help, please open an issue on the new [AWS Amplify CLI ](https://github.com/aws-amplify/amplify-cli) repo, which provides the codegen features and more.
