### ISSUE TITLE
Nothing but comments generated

### ISSUE THREAD

**Issue by teddarling** [awslabs/aws-appsync-codegen#2]
using aws-appsync-codegen version 0.17.2
node version 9.3.0
npm version 5.6.0
typescript version 2.7.2

Given schema.graphql:

```
interface CanAccess {
  groupsCanAccess: [String]
  id: ID!
  owner: String!
  peopleCanAccess: [String]
}

type Mutation {
  createTemplateType(input: CreateTemplateTypeInput!): TemplateType
  deleteTemplateType(input: DeleteTemplateTypeInput!): TemplateType
  updateTemplateType(input: UpdateTemplateTypeInput!): TemplateType
}

type Project implements CanAccess {
  groupsCanAccess: [String]
  id: ID!
  owner: String!
  peopleCanAccess: [String]
  rating: Int
  tags: [String]
  title: String!
}

type Query {
  getTemplateType(id: ID!, title: String!): TemplateType
  listTemplateTypes(after: String, first: Int): TemplateTypeConnection
}

type TemplateType {
  id: ID!
  imageUrl: String
  title: String!
}

type TemplateTypeConnection {
  items: [TemplateType]
  nextToken: String
}

input CreateTemplateTypeInput {
  id: ID!
  imageUrl: String
  title: String!
}

input DeleteTemplateTypeInput {
  id: ID!
  title: String!
}

input UpdateTemplateTypeInput {
  id: ID!
  imageUrl: String
  title: String!
}

```

Then running `aws-appsync-codegen introspect-schema schema.graphql --output schema.json`

Followed by running `aws-appsync-codegen generate **/*.graphql --schema schema.json --target typescript --output operation-result-types.ts` or `aws-appsync-codegen generate schema.graphql --schema schema.json --target typescript --output operation-result-types.ts`

I expect some sort of a file to be generated that has some sort of code. Instead, it generates the following:

```
/* tslint:disable */
//  This file was automatically generated and should not be edited.

```

The following is the Swift result based on README.md

```
//  This file was automatically generated and should not be edited.

import AWSAppSync
```

The following is Flow results based on command in README.md

```
/* @flow */
/* eslint-disable */
//  This file was automatically generated and should not be edited.
```

and nothing more.

I can't say what I expect other than using your docs something that might look like the following, but more robust.

```
export type CharactersQuery = {
  characters: Array<{
    __typename: 'Human',
    name: string,
    homePlanet: ?string
  } | {
    __typename: 'Droid',
    name: string,
    primaryFunction: ?string
  }>
}
```

Same applies if I use any of the other commands in README.md file for generation

**Comment by undefobj** [comment]
Hi @teddarling we're currently investigating.

**Comment by undefobj** [comment]
@teddarling it looks like you're using the SDL file which defines your GraphQL API and not an *.graphql file which has queries and mutations that define the selection set for your operations. 

We have a detailed walk through of this process in the AWS AppSync documentation: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-ios.html

Can you try again with GraphQL queries and/or mutations defined?

**Comment by teddarling** [comment]
So, using the info from your link, I am able to add queries and get things to work using the schema.graphql file downloaded from the AppSync dashboard.

**Comment by undefobj** [comment]
@teddarling great is everything working for you now?
