### ISSUE TITLE
Unknown directive "connection"

### ISSUE THREAD

**Issue by JuHwon** [awslabs/aws-appsync-codegen#20]
When using the [@connection directive](https://www.apollographql.com/docs/react/features/pagination.html#connection-directive)  the codegen throws an error, this is a very useful and important directive for us to work with filtered and paginated queries. 

Error: 
``` bash
> aws-appsync-codegen generate **/*.gql --schema schema.json
.../path/to/query.gql: Unknown directive "connection".
error: Validation of GraphQL query document failed
```

**Comment by JuHwon** [comment]
@rohandubal Are you sure about that? The code generation works fine with my approach if I just remove the `@connection` directive in the queries i am using it.

I do not have a single graphql file which all my specific queries/mutations/subscriptions and fragments.
I also have no intention of creating one. Imo its quite common to use a folder structure like
```
graphql/
  fragments/
  mutations/
  queries/
  subscriptions/
```
In there a i got a seperate .gql file for every fragment/mutation/query and subscription.

It also works fine with apollo-cli codegen which this project is based on according to the docs.  Though the `aws-appsync-codegen` does **not work** with the following query because of the `@connection` directive.

```graphql
#import '../fragments/Blog.gql'

query BlogsConnection($limit: Int!, $tag: BlogTag, $cursor: String) {
  blogsConnection(limit: $limit, tag: $tag, cursor: $cursor) @connection(key: "blogsConnection", filter: ["tag"]) {
    pageInfo {
      cursor
    },
    edges {
      node {
        ...Blog
      }
    }
  }
}
```

I still think this should be considered as a bug.

**Comment by undefobj** [comment]
Hello @JuHwon 

@rohandubal is correct in that you need both an introspection schema as well as the graphql documents. We will be retiring this repo soon as the new [AWS Amplify CLI ](https://github.com/aws-amplify/amplify-cli)has the codegen features and more, including automatic graphql generation as well as a GraphQL transformer:
https://github.com/aws-amplify/amplify-cli/blob/master/native_guide.md

Could you look to see if the new AWS Amplify CLI flow resolves your issue and if not open something in that repo?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If you still need help, please open an issue on the new [AWS Amplify CLI ](https://github.com/aws-amplify/amplify-cli) repo, which provides the codegen features and more.
