### ISSUE TITLE
About --add-s3-wrapper flag for Swift

### ISSUE THREAD

**Issue by Derek-X-Wang** [awslabs/aws-appsync-codegen#4]
Following the doc, [building-a-client-app-ios](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-ios.html#complex-objects), doesn't work.

Let's say we define our SDL like this:
```
type S3Object {
    bucket: String!
    key: String!
    region: String!
}

input S3ObjectInput {
    bucket: String!
    key: String!
    region: String!
    localUri: String
    mimeType: String
}
```

The code generated by aws-appsync-codegen wouldn't compile since S3Object is not defined and cannot convert localUri and mimeType since they are Optional<String?>

I take a look at S3Wrapper.ts, it seems the wrapper is static and add default code regardless of the input. Is that intended?

In my own SDL, I define:
```
input MZS3ObjectInput {
    bucket: String!
    key: String!
    region: String!
    localUri: String!
    mimeType: String!
}
```

So I should change:

`extension S3ObjectInput: AWSS3ObjectProtocol, AWSS3InputObjectProtocol`

to

`extension MZS3ObjectInput: AWSS3ObjectProtocol, AWSS3InputObjectProtocol`

right?

And I need to create an S3Object class?

Otherwise,

`extension MZS3Object: AWSS3ObjectProtocol` wouldn't complile.

Thanks

**Comment by rohandubal** [comment]
Hello @Derek-X-Wang 

Thanks for reporting this issue. Could you provide me with a minimal sample schema where I can reproduce this issue?

Could you also paste the contents of your Podfile? The extension might not be compiling since you may not have a dependency on AWSS3. Could you take dependency on AWSS3?

The issue should not happen if your Podfile has these:

pod 'AWSAppSync', '2.6.7'
pod 'AWSS3', '2.6.6'

Could you please confirm?

Thanks,
Rohan

**Comment by Derek-X-Wang** [comment]
Hi @rohandubal,

Let's use the sample app as an example
[https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios](https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios)

Here is the schema:
```
type Comment {
	# The id of the comment's parent event.
	eventId: ID!
	# A unique identifier for the comment.
	commentId: String!
	# The comment's content.
	content: String!
	# The comment timestamp. This field is indexed to enable sorted pagination.
	createdAt: String!
}

type CommentConnection {
	items: [Comment]
	nextToken: String
}

type DemoS3Object {
	bucket: String!
	key: String!
	region: String!
}

input DemoS3ObjectInput {
	bucket: String!
	key: String!
	region: String!
	localUri: String
	mimeType: String
}

type Event {
	id: ID!
	name: String
	where: String
	when: String
	description: String
	file: DemoS3Object
	# Paginate through all comments belonging to an individual post.
	comments(limit: Int, nextToken: String): CommentConnection
}

type EventConnection {
	items: [Event]
	nextToken: String
}

type Mutation {
	# Create a single event.
	createEvent(
		name: String!,
		when: String!,
		where: String!,
		description: String!,
		file: DemoS3ObjectInput
	): Event
	# Delete a single event by id.
	deleteEvent(id: ID!): Event
	# Comment on an event.
	commentOnEvent(eventId: ID!, content: String!, createdAt: String!): Comment
}

type Query {
	# Get a single event by id.
	getEvent(id: ID!): Event
	# Paginate through events.
	listEvents(limit: Int, nextToken: String): EventConnection
}

type Subscription {
	subscribeToEventComments(eventId: String!): Comment
		@aws_subscribe(mutations: ["commentOnEvent"])
}

schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
```
I add `DemoS3Object`, `DemoS3ObjectInput` and give a new file field for Event.

Here is my graphql file, just a mutation to make it simple:
```
mutation AddEventMutation(
  $name: String!
  $when: String!,
  $where: String!,
  $description: String!,
  $file: DemoS3ObjectInput){
  createEvent(
    name:$name,
    when:$when,
    where:$where,
    description:$description,
    file:$file
  ){
    id
    name
    where
    when
    description
    file {
      bucket
      key
      region
    }
  }
}
```

Then, run:

`aws-appsync-codegen generate GraphQLOperations/*.graphql --schema schema.json --output EventsAPI.swift --add-s3-wrapper`

For my pods, I have AWSAppSync with 2.6.7 and AWSS3 with 2.6.6. So the S3 sdk is imported.

Here is the problem I metioned. No logic is implement by aws-appsync-codegen for s3. It just pastes the code from S3Wrapper.ts
<img width="763" alt="screen shot 2018-03-14 at 1 05 51 am" src="https://user-images.githubusercontent.com/6364170/37390466-6ed4883a-2725-11e8-866d-0ecf0fb55580.png">

I fixed it by creating an S3Object class myself and rename S3ObjectInput in the generated file.

I shouldn't touch the generated file but that the only way to fix right now. It seems that aws-appsync-codegen still lacks s3 support.

Thanks,
Derek

**Comment by rohandubal** [comment]
Hello Derek,

Thanks for your detailed response. I now understand the issue you are facing.

I think our documentation is not very clear on specifying that we have a strict requirement on the `input type` being `S3ObjectInput` and not anything else. The SDK has a protocol of the name `S3ObjectInput` which helps understand that it is a S3 Object based mutation. Same goes for type `S3Object` as SDK uses that protocol to fetch bucket and key to download the objects. I hope this makes it clear.

Do you have an explicit requirement of naming it something like `DemoS3ObjectInput` rather than `S3ObjectInput`? The property names can be anything you desire, just the types have a restriction.

Thanks,
Rohan

**Comment by Derek-X-Wang** [comment]
Hi @rohandubal,

I had tried to use `S3ObjectInput ` and `S3Object` before. It solves the issue of `S3ObjectInput` since `S3ObjectInput` struct is generated by codegen. However, S3Object is still not defined. You can reproduce it via changing the name to `S3ObjectInput ` and `S3Object`.

**Comment by rohandubal** [comment]
Could you update the S3Object to be a fragment in your applications .graphql file as specified here:

https://awslabs.github.io/aws-mobile-appsync-sdk-ios/#client-setup 

This should generate the correct classes for your schema.

Thanks,
Rohan
