### ISSUE TITLE
facing error when code gen for sample app

### ISSUE THREAD

**Issue by fans3210** [awslabs/aws-appsync-codegen#6]
Here are the err msgs:

.../test/appsync-ios-posts-starter/GraphQLOperations/queries.graphql: Cannot query field "getPost" on type "Query".
.../test/appsync-ios-posts-starter/GraphQLOperations/queries.graphql: Cannot query field "allPosts" on type "Query". Did you mean "posts" or "searchPosts"?
.../test/appsync-ios-posts-starter/GraphQLOperations/subscriptions.graphql: Unknown argument "author" on field "newPost" of type "Subscription".
.../test/appsync-ios-posts-starter/GraphQLOperations/subscriptions.graphql: Cannot query field "updatePost" on type "Subscription".
.../test/appsync-ios-posts-starter/GraphQLOperations/subscriptions.graphql: Cannot query field "deletePost" on type "Subscription". Did you mean "newPost"?

I followed instructions from:
https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-ios.html
The above url doesn't have info about where to get schema.json, so I downloaded from the appsync api console. Appreciated if you could give me some help!

**Comment by fans3210** [comment]
I think there are some typing errors for the documentations:

https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-ios.html

Eg: in the graphqlapi, the query named 'posts', while in the query graphql file, named 'allPosts'. Have to correct myself. I'm still new in graphql, quite easy to make such mistakes

**Comment by rohandubal** [comment]
Hello @fans3210 , 

We have an updated set of documentation here:
https://awslabs.github.io/aws-mobile-appsync-sdk-ios/ which should help resolve the issue. 

Could you please go through this and see if it helps resolve the issue?

Thanks
Rohan

**Comment by fans3210** [comment]
Facing a few errors. I don't know whether I'm doing correctly. But I changed some in the graphql file:
I changed
```
query AllPosts {
   listPosts {
    items {
       id
       title
       author
       content
       url
       version
       ups
       downs
      }
   }
}
```

to

```
query AllPosts {
listPosts {

id
title
author
content
url
version
ups
downs
}

}
```
by removing 'items'

I also added the missing contents in the console to make the api to be:

```
input CreatePostInput {
	id: ID!
	author: String!
	title: String
	content: String
	url: String
	ups: Int
	downs: Int
	version: Int!
}

input DeletePostInput {
	id: ID!
}

type Mutation {
	createPost(input: CreatePostInput!): Post
	updatePost(input: UpdatePostInput!): Post
	deletePost(input: DeletePostInput!): Post
}

type Post {
	id: ID!
	author: String!
	title: String
	content: String
	url: String
	ups: Int
	downs: Int
	version: Int!
}

type Query {
	getPost(id: ID!): Post
	listPosts: [Post]
}

type Subscription {
	onCreatePost: Post
		@aws_subscribe(mutations: ["createPost"])
}

input UpdatePostInput {
	id: ID!
	author: String!
	title: String
	content: String
	url: String
	ups: Int
	downs: Int
	version: Int!
}

schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
```

After that the codegen finally works. I don't know whether I missed something or the doc error

**Comment by fans3210** [comment]
After a few attempts. I still fail to subscribe the event of create post. I didn't make any change on update post yet since I'm focusing on create post. Below is a sample project, would be appreciated if anyone could provide some help.

[10Apr-appsync-ios-posts-starter.zip](https://github.com/awslabs/aws-appsync-codegen/files/1893065/10Apr-appsync-ios-posts-starter.zip)

**Comment by hallwest** [comment]
Same issue here, this repo looks dead. where's the aws support?

**Comment by undefobj** [comment]
@hallwest AWS team (@minbi and @rohandubal ) are responding to issues, but it's unclear if the suggested steps have been helpful. The last suggestion from @minbi is correct, the `@aws_subscribe` directive is indented to be used on the GraphQL schema on the server and **not** in the client queries used to generate your Swift file. This is a common mistake hence the suggestion.

To be clear, please reference the flow in the README of this repo where you:
1. Create a GraphQL API, with subscriptions configured
2. Download the introspection schema (**NOT** the GraphQL schema, these are different files)
3. Create one or more GraphQL files with appropriate queries, mutations, and subscriptions
4. Use the introspection schema (it's a json file) from step 2 along with your queries/mutations/subscription files in step 3 to generate a Swift class
5. Call an appropriate GraphQL operation from your iOS app, in the case of a subscription it will be something like:

```
let subscriptionRequest = NewCommentOnPostSubscription(eventId: event!.id)
do {
  newCommentsSubscriptionWatcher = try appSyncClient?.subscribe(subscription: subscriptionRequest, resultHandler: { (res, transaction, err) in
//...handle received data
```

6. Call the mutation that was configured in the service with `@aws_subscribe` which will invoke this subscription

If you're just using GraphQL subscriptions with iOS for the first time, I suggest taking a few minutes and setting up the sample application: https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios
With this sample app you only need to use the built-in schema in the console when you click "Create API" and then download the introspection schema after it completes. This sample schema has the `@aws_subscribe` directive for a mutation on event comments (think of this as comments on a blog post, same pattern). Then clone the repo and configure the appropriate constants and run the codegen. The events.graphql file already has the queries, mutations, and subscriptions created as an example of what is used for codegen.

**Comment by dreamBegin** [comment]
Hello everybody! Just needed a little help
I've Integrated the https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-ios.html Example and that works well for me. 

Then i started something from scratch i have a schema 
```
type Mutation {
	#------ User ------#
	CreateUser(
		FirstName: String,
		Username: String,
		Password: String,
		CreatedOn: Int
	): User
	UpdateUser(UserId: ID!, FirstName: String!, Username: String!): User
	DeleteUser(UserId: ID!): User
}

type Query {
	####------ User ------#
	GetUser(UserId: ID!): User
	CheckUsername(Username: String): [User]
	CheckPhoneNumber(Phone: String): [User]
	#------ Login ------#
	CheckUserLogin(Username: String, Password: String): [User]
}

type User {
	UserId: ID!
	FirstName: String
	Username: String
	#Password: String
	Bio: String
	Phone: String
	Email: String
	Address: String
	WebsiteUrl: String
	ProfilePicture: String
	CreatedOn: Int
	Updated: Int
	Status: Boolean
	LastLoggedIn: Int
	IpAddress: String
}

schema {
	query: Query
	mutation: Mutation
}
```
A simple query in .graphql file

```
query CheckUsername($Username:String){
  CheckUsername(Username:$Username)
  {
      Username
  }
}
```
and generated a file called check Queries.swift

```
import AWSAppSync

public final class CheckUsernameQuery: GraphQLQuery {
    public static let operationString =
    "query CheckUsername {\n  CheckUsername(Username: \"user1_ajm\") {\n    __typename\n    Username\n  }\n}"
    
    public init() {
    }
    
    public struct Data: GraphQLSelectionSet {
        public static let possibleTypes = ["Query"]
        
        public static let selections: [GraphQLSelection] = [
            GraphQLField("CheckUsername", arguments: ["Username": "user1_ajm"], type: .list(.object(CheckUsername.selections))),
            ]
        
        public var snapshot: Snapshot
        
        public init(snapshot: Snapshot) {
            self.snapshot = snapshot
        }
        
        public init(checkUsername: [CheckUsername?]? = nil) {
            self.init(snapshot: ["__typename": "Query", "CheckUsername": checkUsername.flatMap { $0.map { $0.flatMap { $0.snapshot } } }])
        }
        
        public var checkUsername: [CheckUsername?]? {
            get {
                return (snapshot["CheckUsername"] as? [Snapshot?]).flatMap { $0.map { $0.flatMap { CheckUsername(snapshot: $0) } } }
            }
            set {
                snapshot.updateValue(newValue.flatMap { $0.map { $0.flatMap { $0.snapshot } } }, forKey: "CheckUsername")
            }
        }
        
        public struct CheckUsername: GraphQLSelectionSet {
            public static let possibleTypes = ["User"]
            
            public static let selections: [GraphQLSelection] = [
                GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
                GraphQLField("Username", type: .scalar(String.self)),
                ]
            
            public var snapshot: Snapshot
            
            public init(snapshot: Snapshot) {
                self.snapshot = snapshot
            }
            
            public init(username: String? = nil) {
                self.init(snapshot: ["__typename": "User", "Username": username])
            }
            
            public var __typename: String {
                get {
                    return snapshot["__typename"]! as! String
                }
                set {
                    snapshot.updateValue(newValue, forKey: "__typename")
                }
            }
            
            public var username: String? {
                get {
                    return snapshot["Username"] as? String
                }
                set {
                    snapshot.updateValue(newValue, forKey: "Username")
                }
            }
        }
    }
}
```
Then i called this block of code to run the query 

```
let query = CheckUsernameQuery()
AppSyncManager.Client().fetch(query: query, cachePolicy: .fetchIgnoringCacheData) {
    (result, error) in
    if error != nil {
        print(error?.localizedDescription ?? "")
        return
    }
    let username = result?.data?.checkUsername![0]?.username
}
```
And I'm Getting the following response

```
▿ Optional<GraphQLResult<Data>>
  ▿ some : GraphQLResult<Data>
    - data : nil
    - errors : nil
    - source : AWSAppSync.GraphQLResult<Ditto.CheckUsernameQuery.Data>.Source.server
    - dependentKeys : nil
```

The query works well when i test it in Appsync Api panel but not working in the app. No Error, No Data nothing at all? What am i possibly doing wrong if any of you have an idea just free to let me know, it would be a great help for me. Thanks.

**Comment by undefobj** [comment]
The referenced issue confirmed that this was a problem with the wrong schema files being used. @fans3210 please let us know if you're still having trouble. Additionally, we will be retiring this repo soon as the new [AWS Amplify CLI ](https://github.com/aws-amplify/amplify-cli)has the codegen features and more, including automatic graphql generation as well as a GraphQL transformer:
https://github.com/aws-amplify/amplify-cli/blob/master/native_guide.md

Could you look to see if the new AWS Amplify CLI flow resolves your issue and if not open something in that repo?

**Comment by fans3210** [comment]
@undefobj Thanks a lot. Sorry forgot about this issue since it's indeed a schema issue and has been resolved on my side for long time. 

Ok will take a look
